# Generated by Django 4.1.6 on 2023-02-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebToDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
