# Generated by Django 4.1.5 on 2023-02-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameuser", models.CharField(max_length=17, unique=True)),
                ("namefirst", models.CharField(max_length=77)),
                ("namelast", models.CharField(max_length=77)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
