version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_drf_backend
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    # Запуск стандартного сервера django
    # command: bash -c " ./wait-for-postgres.sh db && python manage.py migrate && python manage.py runserver 0.0.0.0:8080 "
    # Запуск сервера Gunicorn
    command: bash -c " ./wait-for-postgres.sh db && python manage.py migrate && gunicorn todo_backend.wsgi -b 0.0.0.0:8080 "
    # Здесь create_data - скрипт, который можно создать, для генерации данных в БД
    # command: bash -c " ./wait-for-postgres.sh db && python manage.py migrate && python manage.py create_data && python manage.py runserver 0.0.0.0:8080 "
    # command: bash -c " python manage.py create_new_user 'root' -p 'root' --admin "

    depends_on:
      - db
  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./todo_frontend_2
    ports:
      - 80:80
    depends_on:
      - nginx
