# Generated by Django 4.1.6 on 2023-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryAuthor',
            new_name='Author',
        ),
    ]
